# ä¸»é¢˜
theme: jekyll-theme-architect

# Site ç«™ç‚¹é…ç½®
title: Youux's Bolg #ç½‘ç«™æ ‡é¢˜
description: ğŸ‘‹ Hey! Guys! Welcome to Star, Fork and Issue #ç½‘ç«™å‰¯æ ‡é¢˜
author: Youux #ä½ çš„åå­—
language: zh-CN #ç½‘ç«™ä½¿ç”¨çš„è¯­è¨€
timezone: Asia/Shanghai #ç½‘ç«™æ—¶åŒº
root: /youux/ #ç½‘ç«™æ ¹ç›®å½•
permalink: :year/:month/:day/:title/ #æ°¸ä¹…é“¾æ¥æ ¼å¼

# Directory ç›®å½•é…ç½®
source_dir: source #èµ„æºæ–‡ä»¶å¤¹ï¼Œè¿™ä¸ªæ–‡ä»¶å¤¹ç”¨æ¥å­˜æ”¾å†…å®¹
public_dir: public #å…¬å…±æ–‡ä»¶å¤¹ï¼Œè¿™ä¸ªæ–‡ä»¶å¤¹ç”¨äºå­˜æ”¾ç”Ÿæˆçš„ç«™ç‚¹æ–‡ä»¶
tag_dir: tags #æ ‡ç­¾æ–‡ä»¶å¤¹
archive_dir: archives #å½’æ¡£æ–‡ä»¶å¤¹
category_dir: categories #åˆ†ç±»æ–‡ä»¶å¤¹
code_dir: downloads/code #Include code æ–‡ä»¶å¤¹
i18n_dir: :lang #å›½é™…åŒ–æ–‡ä»¶å¤¹

# Writing å†™ä½œé…ç½®
new_post_name: :title.md # æ–°æ–‡ç« çš„æ–‡ä»¶åç§°
default_layout: post #é»˜è®¤å¸ƒå±€
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0 #æŠŠæ–‡ä»¶åç§°è½¬æ¢ä¸º (1) å°å†™æˆ– (2) å¤§å†™
render_drafts: false #æ˜¾ç¤ºè‰ç¨¿
post_asset_folder: false #æ˜¯å¦å¯åŠ¨èµ„æºæ–‡ä»¶å¤¹
relative_link: false #æŠŠé“¾æ¥æ”¹ä¸ºä¸æ ¹ç›®å½•çš„ç›¸å¯¹ä½å€
future: true
highlight: #ä»£ç å—çš„è®¾ç½®
enable: true
line_number: true
auto_detect: true
tab_replace:
# Category & Tag åˆ†ç±» & æ ‡ç­¾
default_category: uncategorized #é»˜è®¤åˆ†ç±»
category_map: #åˆ†ç±»åˆ«å
tag_map: #æ ‡ç­¾åˆ«å
# Date / Time format æ—¶é—´å’Œæ—¥æœŸ
date_format: YYYY-MM-DD
time_format: HH:mm:ss
# Pagination åˆ†é¡µ
## Set per_page to 0 to disable pagination
per_page: 10 #æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« é‡ (0 = å…³é—­åˆ†é¡µåŠŸèƒ½)
pagination_dir: page #åˆ†é¡µç›®å½•
