# ä¸»é¢˜
theme: jekyll-theme-architect

# Site ç«™ç‚¹é…ç½®
title: Youux's Bolg #ç½‘ç«™æ ‡é¢˜
description: ğŸ‘‹ Hey! Welcome to Star, Fork and Issue #ç½‘ç«™å‰¯æ ‡é¢˜
author: Youux #ä½ çš„åå­—
language: zh-CN #ç½‘ç«™ä½¿ç”¨çš„è¯­è¨€
timezone: Asia/Shanghai #ç½‘ç«™æ—¶åŒº
root: /youux/ #ç½‘ç«™æ ¹ç›®å½•
permalink: :year/:month/:day/:title/ #æ°¸ä¹…é“¾æ¥æ ¼å¼
